MeshZen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('mesh_search/', include('meshes.urls')),
    path('login_with_zenodo/', include('users.urls')),


    
    ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/urls.py
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('documentation/', views.documentation, name='documentation'),
    path('contact/', views.contact, name='contact'),
    path('features/', views.features, name='features'),
    path('download/', views.download, name='download'),
]

collaboration/urls.py
from django.urls import path

urlpatterns = [
    # Add your URL patterns here
]

documentation/urls.py
from django.urls import path

urlpatterns = [
    # Add your URL patterns here
]

meshes/urls.py
from django.urls import path
from .views import MeshSearchView
from . import views
from django.shortcuts import render

app_name = 'meshes'

urlpatterns = [
    path('mesh_search/', MeshSearchView.as_view(), name='mesh_search'),
        path('results/', views.results, name='results'),
        path('visualize/', views.visualize, name='visualize'),
        path('report/', views.report, name='report'),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login_with_zenodo/', views.login_with_zenodo, name='login_with_zenodo'),
    path('callback_from_zenodo/', views.callback_from_zenodo, name='callback_from_zenodo'),
]

visualizations/urls.py
from django.urls import path

urlpatterns = [
    # Add your URL patterns here
]

base/models.py
from django.db import models

# Create your models here.

collaboration/models.py
from django.db import models

# Create your models here.

documentation/models.py
from django.db import models

# Create your models here.

meshes/models.py
from django.db import models

class ZenodoDeposition(models.Model):
    title = models.CharField(max_length=255)
    deposition_id = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True)
    keywords = models.TextField(blank=True)
    created_date = models.DateTimeField()
    published_date = models.DateTimeField()
    spine_mesh_files = models.ManyToManyField('MeshFile')

class MeshFile(models.Model):
    filename = models.CharField(max_length=255)
    size = models.IntegerField()
    download_url = models.URLField()
    deposition = models.ForeignKey(ZenodoDeposition, on_delete=models.CASCADE)

users/models.py
from django.db import models

# Create your models here.

visualizations/models.py
from django.db import models

# Create your models here.

meshes/forms.py
from django import forms

class MeshSearchForm(forms.Form):
    q = forms.CharField(label='Search', max_length=255, required=False)

base/views.py
from django.shortcuts import render

import os
from django.shortcuts import render
from django.conf import settings


def home(request):
    return render(request, 'base/landing.html')


def about(request):
    return render(request, 'base/about.html')

def documentation(request):
    return render(request, 'base/documentation.html')

def contact(request):
    return render(request, 'base/contact.html')

def features(request):
    return render(request, 'base/features.html')

def download(request):
    return render(request, 'base/download.html')

collaboration/views.py
from django.shortcuts import render

# Create your views here.

documentation/views.py
from django.shortcuts import render

# Create your views here.

meshes/views.py
from django.db.models import Q
from django.views.generic import ListView
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.conf import settings
from .models import ZenodoDeposition, MeshFile
import os
import base64
from io import BytesIO
from django.http import HttpResponse
from django.shortcuts import render
import pymeshlab as ml

def results(request):
    # retrieve data from database or other source
    data = {
        'results': [
            {'field1': 'value1', 'field2': 'value2', 'field3': 'value3'},
            {'field1': 'value4', 'field2': 'value5', 'field3': 'value6'},
        ]
    }
    return render(request, 'meshes/results.html', context=data)


def analyze(request):

    return render(request, 'meshes/fea.html')

def report(request):

    return render(request, 'meshes/report.html')


@method_decorator(csrf_exempt, name='dispatch')
class MeshSearchView(ListView):
    template_name = 'meshes/mesh_search_results.html'
    context_object_name = 'mesh_files'
    paginate_by = settings.PAGINATION_SIZE
    model = MeshFile
    
    def get_queryset(self):
        q = self.request.GET.get('q')
        pi = self.request.GET.get('pi')
        pt = self.request.GET.get('pt')
        ss = self.request.GET.get('ss')
        ll = self.request.GET.get('ll')
        if q or pi or pt or ss or ll :
            mesh_files = MeshFile.objects.all()
            if q:
                mesh_files = mesh_files.filter(Q(filename__icontains=q) | Q(deposition__title__icontains=q))
            if pi:
                mesh_files = mesh_files.filter(pi=pi)
            if pt:
                mesh_files = mesh_files.filter(pt=pt)
            if ss:
                mesh_files = mesh_files.filter(ss=ss)
            if ll:
                mesh_files = mesh_files.filter(ll=ll)
            return mesh_files
        return MeshFile.objects.none()



def visualize(request):
    # Load the mesh using pymeshlab
    mesh_path = os.path.join(settings.STATICFILES_DIRS[0], 'meshes/Vertebra.stl')
    ms = ml.MeshSet()
    ms.load_new_mesh(mesh_path)
    mesh = ms.current_mesh()

    # Simplify the mesh using pymeshlab
    ms2 = ml.MeshSet()
    ms2.add_mesh(mesh)
    ms2.apply_filter('simplification_quadric_edge_collapse_decimation', targetfacenum=1000)
    simplified_mesh = ms2.current_mesh()

    # Write the mesh to an STL file
    stl_path = os.path.join(settings.MEDIA_ROOT, 'meshes/simplified_mesh.stl')
    ms2.save_current_mesh(stl_path)

    # Read the contents of the STL file as a binary string
    with open(stl_path, 'rb') as f:
        stl_contents = f.read()
    base64_stl = base64.b64encode(stl_contents).decode('utf-8')

    # Generate context data for the template
    context = {
        'STATIC_URL': settings.STATIC_URL,
        'mesh_url': 'data:application/stl;base64,' + base64_stl
    }
    return render(request, 'meshes/oops.html', context=context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
import requests

app_name = 'users'


def login_with_zenodo(request):
    # Step 1: Redirect users to Zenodo authentication page
    client_id = 'hSK0EShDLtQ30XCrmAxFTCvAzn759w5qhKwguH9E'
    redirect_uri = 'http://localhost:8000/login_with_zenodo/callback_from_zenodo'
    scope = 'deposit:write deposit:actions'
    url = f'https://zenodo.org/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&scope={scope}'
    return redirect(url)

def callback_from_zenodo(request):
    # Step 2: Obtain access and refresh tokens
    client_id = 'hSK0EShDLtQ30XCrmAxFTCvAzn759w5qhKwguH9E'
    client_secret = 'c43i953RJULF6cfULsLtBWmMbPyhpeUJwnFlP05NWAHkjY091fi2WkSgV4Nl'
    code = request.GET.get('code')
    redirect_uri = 'http://localhost:8000/login_with_zenodo/callback_from_zenodo'
    url = 'https://zenodo.org/oauth/token'
    data = {
        'grant_type': 'authorization_code',
        'code': code,
        'redirect_uri': redirect_uri,
        'client_id': client_id,
        'client_secret': client_secret
    }
    response = requests.post(url, data=data)
    access_token = response.json()['access_token']

    # Step 3: Get user data from Zenodo API
    headers = {'Authorization': f'Bearer {access_token}'}
    user_url = 'https://zenodo.org/api/deposit/depositions'
    response = requests.get(user_url, headers=headers)
    user_data = response.json()

    # Step 4: Create or authenticate user in Django database
    user_id = user_data[0]['userId']
    email = user_data[0]['email']
    name = user_data[0]['name']
    username = email.split('@')[0]
    password = User.objects.make_random_password()
    user, created = User.objects.get_or_create(username=username, email=email, first_name=name)
    if created:
        user.set_password(password)
        user.save()
    user = authenticate(request, username=username, password=password)
    login(request, user)

    return redirect('base:home')

visualizations/views.py
from django.shortcuts import render

# Create your views here.

MeshZen/templates/documentation/documentation.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-4">
    <h2>Documentation</h2>
    <hr>
    <h4>Searching for Spine Meshes on Zenodo</h4>
    <p>
      To search for publicly available spine meshes on Zenodo using MeshZen, simply enter your search criteria into the search bar on the landing page and click the "Search" button. You can search by keywords, author, or other criteria such as spine pathology, age group, or imaging modality.
    </p>
    <p>
      Once you have submitted your search query, MeshZen will use the Zenodo API to retrieve the metadata for spine mesh depositions on Zenodo that match your criteria. The search results will be displayed in a nicely formatted list, along with a 3D preview of each mesh that you can interactively explore.
    </p>
    <h4>Filtering Spine Meshes by Criteria</h4>
    <p>
      If you want to narrow down your search results further, you can use the filters provided on the search page to filter spine meshes by specific criteria such as anatomical region, spine pathology, or imaging modality. As you select different filter options, the search results will be dynamically updated to reflect your selections.
    </p>
    <h4>Viewing and Modifying Spine Meshes on Zenodo</h4>
    <p>
      If you find a spine mesh that you are interested in, you can click on the corresponding item in the search results to view more details about the mesh, including additional metadata such as the name of the research group that generated it, the imaging modality used, and the license under which it is released. If you want to modify the mesh or use it in your own research, you will need to log in to Zenodo using your Zenodo credentials.
    </p>
    <p>
      Once you have logged in, you will be able to access and modify the spine mesh directly on Zenodo, and any changes that you make will be automatically synced back to the Disc4all deposition (or any other deposition you choose to log in from). To download the mesh for use in your own research, simply click the "Download" button on the Zenodo page.
    </p>
  </div>
{% endblock %}

templates/base/about.html
{% extends 'base/base.html' %}

{% block content %}
    <section class="api">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2>API Documentation</h2>
                    <p>Explore MeshZen's API and integrate it with your applications.</p>
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-md-6">
                    <h3>Authentication</h3>
                    <p>MeshZen API requires authentication with Zenodo credentials.</p>
                </div>
                <div class="col-12 col-md-6">
                    <h3>Endpoints</h3>
                    <p>The MeshZen API provides access to the following endpoints:</p>
                    <ul>
                        <li><strong>/api/meshes/</strong> - Retrieve a list of meshes</li>
                        <li><strong>/api/meshes/{id}/</strong> - Retrieve a specific mesh by ID</li>
                        <li><strong>/api/meshes/{id}/comments/</strong> - Retrieve comments for a specific mesh</li>
                        <li><strong>/api/meshes/{id}/comments/create/</strong> - Add a new comment to a specific mesh</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/base/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css">
    <script src="https://aframe.io/releases/1.2.0/aframe.min.js"></script>
    <script src="/static/js/aframe.min.js"></script>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"  crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" rel="stylesheet">

    <!-- Custom CSS -->

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'base:home' %}">MeshZen</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link {% if request.path == '/' %}active{% endif %}" aria-current="page" href="{% url 'base:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.path == '/features/' %}active{% endif %}" href="{% url 'base:features' %}">Features</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.path == '/documentation/' %}active{% endif %}" href="{% url 'base:documentation' %}">Documentation</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.path == '/download/' %}active{% endif %}" href="{% url 'base:download' %}">Download</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.path == '/about/' %}active{% endif %}" href="{% url 'base:about' %}">API</a>
              </li>
            </ul>
            <div class="d-flex">
              <a href="{% url 'login_with_zenodo' %}" class="btn btn-outline-dark me-2"><i class="fab fa-zenodo"></i> Login with Zenodo</a>
            </div>
          </div>
        </div>
      </nav>
      

    <div class="container-fluid">
        <br>
      {% block content %}{% endblock %}
      <br><br>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <footer class="bg-black text-white py-3 position-fixed bottom-0 w-100">
      <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto text-center">
                <img src="{% static 'images/istlogo.png' %}" alt="Logo" style="width:30%">
            </div>
        </div>
    </div>
    
    </footer>

      </style>
      
    


    <!-- Optional JavaScript -->

<script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"></script>
</body>
</html>

templates/base/documentation.html
{% extends 'base/base.html' %}

{% block content %}
  <div class="container mt-4">
    <h2>Documentation</h2>
    <hr>
    <h4>Searching for Spine Meshes on Zenodo</h4>
    <p>
      To search for publicly available spine meshes on Zenodo using MeshZen, simply enter your search criteria into the search bar on the landing page and click the "Search" button. You can search by keywords, author, or other criteria such as spine pathology, age group, or imaging modality.
    </p>
    <p>
      Once you have submitted your search query, MeshZen will use the Zenodo API to retrieve the metadata for spine mesh depositions on Zenodo that match your criteria. The search results will be displayed in a nicely formatted list, along with a 3D preview of each mesh that you can interactively explore.
    </p>
    <h4>Filtering Spine Meshes by Criteria</h4>
    <p>
      If you want to narrow down your search results further, you can use the filters provided on the search page to filter spine meshes by specific criteria such as anatomical region, spine pathology, or imaging modality. As you select different filter options, the search results will be dynamically updated to reflect your selections.
    </p>
    <h4>Viewing and Modifying Spine Meshes on Zenodo</h4>
    <p>
      If you find a spine mesh that you are interested in, you can click on the corresponding item in the search results to view more details about the mesh, including additional metadata such as the name of the research group that generated it, the imaging modality used, and the license under which it is released. If you want to modify the mesh or use it in your own research, you will need to log in to Zenodo using your Zenodo credentials.
    </p>
    <p>
      Once you have logged in, you will be able to access and modify the spine mesh directly on Zenodo, and any changes that you make will be automatically synced back to the Disc4all deposition (or any other deposition you choose to log in from). To download the mesh for use in your own research, simply click the "Download" button on the Zenodo page.
    </p>
    <br><br>
  </div>
{% endblock %}

templates/base/download.html
{% extends 'base/base.html' %}

{% block content %}
    <section class="download">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2>Download</h2>
                    <p>Download the latest version of MeshZen to get started.</p>
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Stable Release</h3>
                            <p class="card-text">The latest stable release of MeshZen, tested and ready for production use.</p>
                            <a href="#" class="btn btn-primary">Download Now</a>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Development Release</h3>
                            <p class="card-text">The latest development release of MeshZen, with the newest features and bug fixes.</p>
                            <a href="#" class="btn btn-primary">Download Now</a>
                        </div>
                    </div>
                </div>
            </div>
            </div>
            </section>
            {% endblock %}

templates/base/landing.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<section class="hero">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-6">
        <h1><img src="https://www.svgrepo.com/show/45090/spine.svg" style="width:10%">MeshZen</h1>
        <p>Discover, visualize and collaborate on 3D spine meshes.</p>

            <div class="container">
              <a href="{% url 'meshes:mesh_search' %}" class="btn btn-primary">Explore</a>
              <a href="#" class="btn btn-secondary">GitHub</a>
            </div>

      </div>
      <div class="col-12 col-md-6">
        <div class="mesh-preview">
          <div class="preview-box">
            <div class="preview">
              <div id="vtk_container" style="width:100%; height: 500px;"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<br>



<script src="https://unpkg.com/vtk.js"></script>

<script>
    // Create a renderer, render window, and interactor
    var renderer = vtk.Rendering.Misc.vtkRenderer.newInstance({background: [0.2, 0.2, 0.2]});
    var renderWindow = vtk.Rendering.Core.vtkRenderWindow.newInstance();
    renderWindow.addRenderer(renderer);
    var interactor = vtk.Rendering.Core.vtkRenderWindowInteractor.newInstance();
    interactor.setView(renderWindow);
    interactor.initialize();
    interactor.bindEvents(document.getElementById('vtk_container'));

    // Add the actor to the scene
    renderer.addActor({{ actor }});

    // Render the scene
    renderWindow.render();
</script>

{% endblock %}

templates/meshes/fea.html
{% extends 'base/base.html' %}

{% block content %}
  <div class="container">
    <h1>Finite Element Analysis</h1>
    <hr>
    <h3>Mesh Selection</h3>
    <div class="form-group">
      <label for="mesh-select">Select a Mesh:</label>
      <select class="form-control" id="mesh-select">
        <option value="">-- Select a Mesh --</option>
        <option value="mesh1">Mesh 1</option>
        <option value="mesh2">Mesh 2</option>
        <option value="mesh3">Mesh 3</option>
        <!-- Add more options here -->
      </select>
    </div>
    <hr>
    <h3>Material Properties</h3>
    <div class="form-group">
      <label for="youngs-modulus-input">Young's Modulus:</label>
      <input type="number" class="form-control" id="youngs-modulus-input" placeholder="Enter Young's Modulus">
    </div>
    <div class="form-group">
      <label for="poissons-ratio-input">Poisson's Ratio:</label>
      <input type="number" class="form-control" id="poissons-ratio-input" placeholder="Enter Poisson's Ratio">
    </div>
    <hr>
    <h3>Boundary Conditions</h3>
    <div class="form-group">
      <label for="left-bc-select">Left Boundary Condition:</label>
      <select class="form-control" id="left-bc-select">
        <option value="">-- Select a Boundary Condition --</option>
        <option value="fixed">Fixed</option>
        <option value="free">Free</option>
        <option value="force">Force</option>
        <!-- Add more options here -->
      </select>
    </div>
    <div class="form-group">
      <label for="right-bc-select">Right Boundary Condition:</label>
      <select class="form-control" id="right-bc-select">
        <option value="">-- Select a Boundary Condition --</option>
        <option value="fixed">Fixed</option>
        <option value="free">Free</option>
        <option value="force">Force</option>
        <!-- Add more options here -->
      </select>
    </div>
    <hr>
    <h3>Load Case</h3>
    <div class="form-group">
      <label for="load-type-select">Load Type:</label>
      <select class="form-control" id="load-type-select">
        <option value="">-- Select a Load Type --</option>
        <option value="point-load">Point Load</option>
        <option value="distributed-load">Distributed Load</option>
        <!-- Add more options here -->
      </select>
    </div>
    <div class="form-group">
      <label for="load-value-input">Load Value:</label>
      <input type="number" class="form-control" id="load-value-input" placeholder="Enter Load Value">
    </div>
    <hr>
    <a href=" {% url 'meshes:report' %} " class="btn btn-dark">Run Analysis</a>    </div>
</div>
  <br>
{% endblock %}

templates/meshes/mesh_search_results.html
{% extends 'base/base.html' %}

{% block content %}

<div class="container">
  <h1>Spine Mesh Search</h1>
  <form class="form-inline" method="post" action="{% url 'meshes:results' %}">
    {% csrf_token %}
    <br>
    <div class="form-group">
        <label for="spinopelvic_param">Spinopelvic Parameters:</label>
        <div class="slider-wrapper">
            PI
            <input type="range" min="-3" max="3" value="0" class="slider" id="pi_slider" name="pi">
            <span class="slider-value">PI: 0</span>
        </div>
        <div class="slider-wrapper">
            PT
            <input type="range" min="-3" max="3" value="0" class="slider" id="pt_slider" name="pt">
            <span class="slider-value">PT: 0</span>
        </div>
        <div class="slider-wrapper">
            SS
            <input type="range" min="-3" max="3" value="0" class="slider" id="ss_slider" name="ss">
            <span class="slider-value">SS: 0</span>
        </div>
        <div class="slider-wrapper">
            LL
            <input type="range" min="-3" max="3" value="0" class="slider" id="ll_slider" name="ll">
            <span class="slider-value">LL: 0</span>
        </div>
    </div>
    <br>

    <br>
    <button type="submit" class="btn btn-primary ml-2">Search</button>
  </form>

  {% if object_list %}
    <h2>Search Results</h2>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Deposition ID</th>
          <th scope="col">Title</th>
          <th scope="col">Description</th>
          <th scope="col">Creator</th>
          <th scope="col">Publication Date</th>
        </tr>
      </thead>
      <tbody>
        {% for mesh in object_list %}
          <tr>
            <td><a href="{{ mesh.url }}">{{ mesh.deposition_id }}</a></td>
            <td>{{ mesh.title }}</td>
            <td>{{ mesh.description }}</td>
            <td>{{ mesh.creator }}</td>
            <td>{{ mesh.publication_date }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}
</div>

<script>
  // Get the sliders and slider values
  const pi_slider = document.getElementById("pi_slider");
  const pt_slider = document.getElementById("pt_slider");
  const ss_slider = document.getElementById("ss_slider");
  const ll_slider = document.getElementById("ll_slider");
  const pi_value = document.querySelector("#pi_slider + span.slider-value");
  const pt_value = document.querySelector("#pt_slider + span.slider-value");
  const ss_value = document.querySelector("#ss_slider + span.slider-value");
  const ll_value = document.querySelector("#ll_slider + span.slider-value");

  // Update the slider value when the user moves the slider
 // Update the slider value when the user moves the slider
pi_slider.addEventListener("input", function() {
pi_value.textContent = this.value;
});

pt_slider.addEventListener("input", function() {
pt_value.textContent = this.value;
});

ss_slider.addEventListener("input", function() {
ss_value.textContent = this.value;
});

ll_slider.addEventListener("input", function() {
ll_value.textContent = this.value;
});

// Get the form and add an event listener to it
const form = document.querySelector("#mesh-search-form");
form.addEventListener("submit", function(event) {
// Prevent the form from submitting
event.preventDefault();

// Get the spinopelvic parameters from the sliders
const pi = pi_slider.value;
const pt = pt_slider.value;
const ss = ss_slider.value;
const ll = ll_slider.value;


// Send a POST request to the server with the spinopelvic parameters and GAP Score
const xhr = new XMLHttpRequest();
xhr.open("POST", "{% url 'meshes:mesh_search' %}");
xhr.setRequestHeader("Content-Type", "application/json");
xhr.onload = function() {
if (xhr.status === 200) {
// Update the search results with the response from the server
const search_results = document.querySelector("#search-results");
search_results.innerHTML = xhr.responseText;
} else {
alert("Error: " + xhr.statusText);
}
};
const data = JSON.stringify({pi: pi, pt: pt, ss: ss, ll: ll});
xhr.send(data);
});
</script>
{% endblock %}

templates/meshes/meshes.html
<!DOCTYPE html>
<html>
<head>
	<title>Rendered Mesh</title>
</head>
<body>
	<img src="data:image/png;base64,{{ image }}" />
</body>
</html>

templates/meshes/results.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}
  <div class="container">
    <h1>Mesh Values</h1>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Filename</th>
          <th scope="col">PI</th>
          <th scope="col">PT</th>
          <th scope="col">SS</th>
          <th scope="col">LL</th>
        </tr>
      </thead>
      <tbody>
        {% for mesh in meshes %}
          <tr>
            <td>{{ mesh.id }}</td>
            <td>{{ mesh.filename }}</td>
            <td>{{ mesh.pi }}</td>
            <td>{{ mesh.pt }}</td>
            <td>{{ mesh.ss }}</td>
            <td>{{ mesh.ll }}</td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="6">No Mesh Values Found</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <hr>
    <div class="text-center">
      <a href="" class="btn btn-primary mx-2">Download Meshes</a>
      <a href=" {% url 'meshes:visualize' %} " class="btn btn-dark">Visualize</a>    </div>
  </div>
  
  </div>
{% endblock %}